[package]
name = "Timeliner"
version = "0.1.0"
authors = ["duangsuse <fedora-opensuse@outlook.com>"]
license = "MIT"

[dependencies]
tokio-minihttp = "0.1.0"
lazy_static = "0.1.0"
serde_json = "1.0.9"
tokio-signal = "0.1"
websocket = "0.20.2"
